sudo: required
dist: bionic
services:
  - docker
jdk:
  - openjdk9
addons:
  apt:
    update: true
    packages:
      - openvswitch-switch
install:
  - set -e
  - bin/setup_daq
script:
  - set -e
  - bin/test_daq
cache: pip
env:
  global:
    - DOCKER_STARTUP_TIMEOUT_MS=60000
  matrix:
    - DAQ_TEST=base
    - DAQ_TEST=dhcp TEST=1
    - DAQ_TEST=dhcp TEST=2
    - DAQ_TEST=dhcp TEST=3
    - DAQ_TEST=dhcp TEST=4
branches:
  except:
  - /^release-\d+\.\d+(\.\d+)?$/
