dps:
  alt-switch:
    dp_id: 2
    interfaces:
      1:
        native_vlan: 2000
      2:
        native_vlan: 2001
      3:
        native_vlan: 2002
      4:
        native_vlan: 2003
      5:
        native_vlan: 2004
      10:
        tagged_vlans: [2000, 2001, 2002, 2003, 2004, 121]
      11:
        native_vlan: 121
